### PR TITLE
Move publicaton data from intent extras to global variable

### PR DESCRIPTION
**Pull request by qnga**
A real-sized Publication containing media overlays is too large to be passed from one activity to another as intent extras.
Use instead a global variable named CURRENT_PUB in the navigator package.

### CODE REVIEW

**Comment by mickael-menu** [comment]
Thank you for your contribution.
I can see two issues with a global var to fix this problem though:
- The navigator can potentially be used to display several books at the same time (e.g. multi-window)
- Setting a global var doesn't convey the intent of the public API very clearly

How about implementing a `PublicationRepository` interface provided by `r2-navigator`, and sending only the publication ID with the `Intent`? This would require initializing R2 with the concrete implementation during app startup.

**Comment by mickael-menu** [comment]
See my comment on the other related PR: https://github.com/readium/r2-testapp-kotlin/pull/285#issuecomment-577238114

**Comment by qnga** [comment]
Sure, I didn't think about that. Your solution is fine, but requires to import a basic concept of library into the Navigator. I'm not sure whether it is really an issue or not. 
If it is, we could be a little more abstract and rather implement a session mechanism to identify each reading activity and deliver it the right publication. It might be reused for other purposes later.
TestApp.startActivity(pub) {
	token = Navigator.getNewActivityToken()
	Navigator.activityRegister[token] = pub
       intent.token = token
	startActivity(intent)
}

Navigator.startActivity(pub) {
	publication = Navigator.activityRegister[intent.token]
}

**Comment by mickael-menu** [comment]
Not really a library, it can be implemented in many ways and most likely a simple in-memory dictionary by the host app.

```kotlin
interface PublicationRepository {
    fun getPublication(id: String): Publication?
}
```
I feel like sending object IDs through Intents is more idiomatic.

However, a "session" registry sounds more flexible and could be useful later on. I guess we should have this conversation in the context of the [Navigator API](https://github.com/readium/architecture/blob/master/navigator/public-api.md) that will be implemented in Kotlin soon-ish.

If we go this way, we might want to wrap this session management and keep it private to the navigator:

```kotlin
fun Navigator.createIntent(packageContext: Context, publication: Publication) {
    token = getNewActivityToken()
    activityRegister[token] = pub
    return Intent(packageContext, this).apply {
        putExtra("token", token)
    }
}

startActivity(Navigator.createIntent(this, publication))
```

(One thing to keep in mind is that we might have leaks with a session registry, for example if the Intent is discarded before being started)

**Comment by qnga** [comment]
Since media overlays are still in discussion, what about keeping Publication objects small by keeping Media Overlays content outside? Publication objects may contain basically data for the manifest, not much more.
The library pushes the manifest into the intent and calls the addEpub method from the server, which in his turn adds routes to Media Overlays. At this point there are two alternatives : either the SMIL files get converted by the fetcher on the fly (maybe the browser can be asked to prefetch media overlays), or the server parses SMIL files, create MediaOverlays object and wait for serving it.

**Comment by mickael-menu** [comment]
We'll have to see with @HadrienGardeur for the MediaOverlays model, I think at some point it was considered to have a `Link` in the `Publication` object that would point to another JSON object containing the media overlays.

It's pretty safe to assume that EPUB contents will always be served through an HTTP server, but we need to be careful as it might not always be the case depending on the format.

In any case, we still need to address the problem that your PR fixes – I opened an issue for that: https://github.com/readium/r2-testapp-kotlin/issues/286 – because `Publication` can be much larger, I've seen some EPUB with a thousand reading order items. There's also other objects that we'll probably need to send to the Navigator, such as the `DRMLicense` to handle LCP copy rights (https://github.com/readium/r2-testapp-kotlin/issues/266).

**Pull request closed without merging**
